models:
  - name: "user"
    fields: 
      - name: "id"
        type: "string"
      - name: "name"
        type: "string"
        default-value: ""
  - name: "profile"
    fields:
      - name: "id"
        type: "string"
      - name: "user"
        type: "@user"
        default-value:
          id: ""
          name: ""
  - name: "external"
    external-model: "filename.proto/MessageName"
tables:
  - name: "users"
    storage-path: "users"
    columns:
      - name: "id"
        type: "string"
      - name: "name"
        type: "string"
        default-value: "ivan"
      - name: "age"
        type: "uint64"
        default-value: 18
    pk:
      - "id"
    range-indexes: 
      - name: "name-index"
        ik: 
          - "name"
        columns:
          - "id"
          - "name"
          - "age"
        async: false